spring.application.name=inpatientservice

#server

server.port=8989

# Oracle DataSource

spring.datasource.url=jdbc:oracle:thin:@seoulit.pe.kr:1521/freepdb1
spring.datasource.username=inpatient
spring.datasource.password=inpatient
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=true

# mybatis

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:/mapper/*.xml