-- 병상 확장 (2026-10-05) — 16개 → 55개
-- 병동당: 특실(VIP, 04) 1실 1병상 + 1인실(01) 2실 + 다인실(02, 4인실) 2실 = 11병상
-- 사용중/예약 병상은 상태와 환자를 그대로 두고, 병실 유형만 정리하고 병상을 추가함
-- 다시 실행해도 같은 병상이 중복으로 들어가지 않음 (NOT EXISTS)
-- 병실 유형은 ROOM_TYPE_CODE에만 넣음 (ROOM_TYPE_CD는 코드에서 쓰지 않는 예전 컬럼)

-- 1) 병상이 2개인데 1인실로 되어 있던 105·108호를 다인실로 정리 (105A·108A 사용중 → 병상은 그대로 둠)
UPDATE bed SET room_type_code = '02', updated_at = SYSTIMESTAMP WHERE room_no IN ('105', '108') AND room_type_code = '01';

-- 2) 기존 다인실을 4인실로 채우고, 병동마다 특실·1인실·다인실 추가
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-102B', '01', '102', 'B', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-102B');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-102C', '01', '102', 'C', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-102C');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-102D', '01', '102', 'D', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-102D');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-103A', '02', '103', 'A', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-103A');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-103C', '02', '103', 'C', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-103C');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-103D', '02', '103', 'D', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-103D');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-105C', '03', '105', 'C', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-105C');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-105D', '03', '105', 'D', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-105D');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-106C', '03', '106', 'C', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-106C');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-106D', '03', '106', 'D', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-106D');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-107C', '04', '107', 'C', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-107C');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-107D', '04', '107', 'D', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-107D');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-108C', '04', '108', 'C', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-108C');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-108D', '04', '108', 'D', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-108D');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-109C', '05', '109', 'C', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-109C');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-109D', '05', '109', 'D', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-109D');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-110C', '05', '110', 'C', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-110C');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-110D', '05', '110', 'D', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-110D');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-111A', '01', '111', 'A', 'EMPTY', '04', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-111A');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-112A', '01', '112', 'A', 'EMPTY', '01', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-112A');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-113A', '01', '113', 'A', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-113A');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-113B', '01', '113', 'B', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-113B');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-113C', '01', '113', 'C', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-113C');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-113D', '01', '113', 'D', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-113D');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-114A', '02', '114', 'A', 'EMPTY', '04', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-114A');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-115A', '02', '115', 'A', 'EMPTY', '01', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-115A');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-116A', '02', '116', 'A', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-116A');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-116B', '02', '116', 'B', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-116B');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-116C', '02', '116', 'C', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-116C');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-116D', '02', '116', 'D', 'EMPTY', '02', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-116D');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-117A', '03', '117', 'A', 'EMPTY', '04', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-117A');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-118A', '03', '118', 'A', 'EMPTY', '01', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-118A');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-119A', '03', '119', 'A', 'EMPTY', '01', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-119A');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-120A', '04', '120', 'A', 'EMPTY', '04', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-120A');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-121A', '04', '121', 'A', 'EMPTY', '01', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-121A');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-122A', '04', '122', 'A', 'EMPTY', '01', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-122A');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-123A', '05', '123', 'A', 'EMPTY', '04', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-123A');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-124A', '05', '124', 'A', 'EMPTY', '01', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-124A');
INSERT INTO bed (bed_id, ward_cd, room_no, bed_no, bed_status, room_type_code, created_at, updated_at) SELECT 'BED-125A', '05', '125', 'A', 'EMPTY', '01', SYSTIMESTAMP, SYSTIMESTAMP FROM dual WHERE NOT EXISTS (SELECT 1 FROM bed WHERE bed_id = 'BED-125A');

COMMIT;
